DISPLAY_RES = (900, 1200)

ROI_TOP = 80
ROI_LEFT = 100
ROI_HEIGHT = 200
ROI_WIDTH = int(ROI_HEIGHT * DISPLAY_RES[1] / DISPLAY_RES[0])


def crop_roi(x):
    return x[..., ROI_TOP : ROI_TOP + ROI_HEIGHT, ROI_LEFT : ROI_LEFT + ROI_WIDTH]
